language: cpp
compiler: gcc
script:
  - make all
  - make tests
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
        env:
            - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
    - eval "${MATRIX_EVAL}"

